# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI + CD

on:
  push:
    branches: [ "main" ]
  #pull_request:    # probably shouldn't do a full deploy if it's just a PR
  #  branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "gh-pages"
  cancel-in-progress: false

jobs:
  setup:
    runs-on: ubuntu-latest
    
    environment: github-pages

    strategy: # TODO: strategy needs to be moved out of setup job
      matrix:
        node-version: [v20.x]  # can add different versions of node here

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci

    - name: Save Runner # each step runs on a fresh instance (possibly just merge setup and testing?)
      uses: actions/cache/save@v4
      with:
        path: ~/
        key: ${{ github.sha }}

  test:
    needs: setup

    runs-on: ubuntu-latest
    
    environment: github-pages

    steps:
    - name: Restore Runner
      uses: actions/cache/restore@v4
      id: restore-cache
      with:
        path: ~/
        key: ${{ github.sha }} # TODO: handle a cache miss by manually setting up again
        fail-on-cache-miss: true


    - name: Run Node.js Tests # TODO: Decide on and add a testing framework, both for the React frontend and the Node.js / C++ / WASM backend
      run: npm run test

    - name: Save Runner
      uses: actions/cache/save@v4
      with:
        path: ~/
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
      
  build:
    needs: [test, setup]

    runs-on: ubuntu-latest
    
    environment: github-pages

    steps:
    - name: Restore Runner
      uses: actions/cache/restore@v4
      id: restore-cache
      with:
        path: ~/
        key: ${{ github.sha }} # TODO: handle a cache miss by setting up and testing again
        fail-on-cache-miss: true

    - name: Transpile Typescript + Build w/ Vite
      run: npm run build

    - name: Upload Build Artifact
      uses: actions/upload-pages-artifact@v3
      with: 
        path: ./dist  # Vite deploys to dist, not build folder

      # no need to save runner here since deployment doesn't require the project (the artifact has been uploaded)

  deploy:
    needs: [test, setup, build]

    runs-on: ubuntu-latest

    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
