# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI + CD

on:
  push:
    branches: [ "main" ]
  #pull_request:    # probably shouldn't do a full deploy if it's just a PR
  #  branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "gh-pages" # this is basically a mutex key
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    
    environment: github-pages # for importing any relevant environment variables (use env object)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ env.USE_NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.USE_NODE_VERSION }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci

    - name: Run Node.js Tests # TODO: We've decided on Mocha.js + Chai?
      run: npm run test
      
  build:
    runs-on: ubuntu-latest
    
    environment: github-pages

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.USE_NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.USE_NODE_VERSION }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Transpile Typescript + Build w/ Vite
      run: npm run build

    - name: Upload Build Artifact
      uses: actions/upload-pages-artifact@v3
      with: 
        path: ./dist  # Vite deploys to dist, not build folder
        name: github-pages-${{ github.sha }}
        retention-days: 90

      # no need to save runner here since deployment doesn't require the project (the artifact has been uploaded)

  deploy:
    needs: [test, build]

    runs-on: ubuntu-latest

    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages-${{ github.sha }}
