# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, run tests
# and then deploy to a GitHub pages website.

name: CI + CD

on:
  push:
    branches: [ "main" ]
  #pull_request:    # probably shouldn't do a full deploy if it's just a PR
  #  branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "gh-pages" # this is basically a mutex key
  cancel-in-progress: false

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages  # for importing any relevant environment variables (use env object)
      url: ${{ steps.deployment.outputs.page_url }}  # includes URL on github deploy UI graph

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ env.USE_NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.USE_NODE_VERSION }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci

    - name: Run Mocha + Chai Tests # TODO: We've decided on Mocha.js + Chai?
      run: npm run test

    - name: Transpile Typescript + Build w/ Vite
      run: npm run build

    - name: Upload Build Artifact
      uses: actions/upload-pages-artifact@v3
      with: 
        path: ./dist  # Vite deploys to dist, not build folder
        name: github-pages-${{ github.sha }}  # TODO: get a consistent hash across pull requests and pushes to main
        retention-days: 90

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages-${{ github.sha }}
