# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI + CD

on:
  push:
    branches: [ "main" ]
  #pull_request:    # probably shouldn't do a full deploy if it's just a PR
  #  branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "gh-pages"
  cancel-in-progress: false

jobs:
  setup:
    runs-on: ubuntu-latest
    
    environment: github-pages

    strategy:
      matrix:
        node-version: [v20.x]  # can add different versions of node here

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci

  test:
    needs: setup

    runs-on: ubuntu-latest
    
    environment: github-pages

    steps:  
    - name: Run Node.js Tests # TODO: Decide on and add a testing framework, both for the React frontend and the Node.js / C++ / WASM backend
      run: npm run test
      
  build:
    needs: [test, setup]

    runs-on: ubuntu-latest
    
    environment: github-pages

    steps:
    - name: Transpile Typescript + Build w/ Vite
      run: npm run build

    - name: Upload Build Artifact
      uses: actions/upload-pages-artifact@v3
      with: 
        path: ./dist  # Vite deploys to dist, not build folder

  deploy:
    needs: [test, setup, build]

    runs-on: ubuntu-latest

    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
