# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, run tests
# and then deploy to a GitHub pages website.

name: Testing & Building

on:
  push: # test on all pushes except to main and any branch that includes 'notest' or 'skiptest'
    branches-ignore:
      - 'main'
      - '**notest**'
      - '**skiptest**'
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "gh-pages" # this is basically a mutex key
  cancel-in-progress: false

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    environment:
      name: github-pages  # for importing any relevant environment variables (use env object)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ env.USE_NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.USE_NODE_VERSION }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci

    - name: Run Mocha Tests
      run: npm run test

    - name: Transpile Typescript + Build w/ Vite
      run: npm run build

    - name: Upload Build Artifact
      uses: actions/upload-pages-artifact@v3
      with: 
        path: ./dist  # Vite deploys to dist, not build folder
        name: github-pages-${{ (github.event_name == 'pull_request') && (github.event.pull_request.head.sha) || (github.sha) }}  # TODO: get a consistent hash across pull requests and pushes to main
        retention-days: 14  # lower retention since this event will trigger a lot more
